CREATE TABLE Users (
UserID INT IDENTITY(700000,1) CONSTRAINT UserID_pk PRIMARY KEY,
FirstName NVARCHAR(20) NULL,
LastName NVARCHAR(20) NOT NULL,
EmailID NVARCHAR(100) UNIQUE NOT NULL,
PhoneNumber CHAR(10) UNIQUE NOT NULL,
CountryCode CHAR(3) NOT NULL,
Password NVARCHAR(50) NOT NULL,
WalletID INT NOT NULL UNIQUE,
DateAdded DATETIME NOT NULL,
Gender CHAR(1) NOT NULL,
DateOfBirth DATETIME NOT NULL,
SubscriptionPerid_inDays INT NULL,
SubsscriptionTypeID INT NOT NULL ,
SubscriptionStartDate DATETIME NULL,
CONSTRAINT SubTypeID_fk FOREIGN KEY (SubsscriptionTypeID) REFERENCES Subscription(SubID),
CONSTRAINT WalletID_fk FOREIGN KEY (WalletID) REFERENCES Wallet(WalletID)
);

